/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BinsRouteImport } from './routes/bins'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrucksRouteImport } from './routes/trucks'
import { Route as ApiPublicSensorsRouteImport } from './routes/api/public/sensors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BinsRoute = BinsRouteImport.update({
  id: '/bins',
  path: '/bins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksRoute = TrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSensorsRoute = ApiPublicSensorsRouteImport.update({
  id: '/api/public/sensors',
  path: '/api/public/sensors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/bins': typeof BinsRoute
  '/dashboard': typeof DashboardRoute
  '/live-map': typeof LiveMapRoute
  '/optimizer': typeof OptimizerRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trucks': typeof TrucksRoute
  '/api/public/sensors': typeof ApiPublicSensorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/bins': typeof BinsRoute
  '/dashboard': typeof DashboardRoute
  '/live-map': typeof LiveMapRoute
  '/optimizer': typeof OptimizerRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trucks': typeof TrucksRoute
  '/api/public/sensors': typeof ApiPublicSensorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/bins': typeof BinsRoute
  '/dashboard': typeof DashboardRoute
  '/live-map': typeof LiveMapRoute
  '/optimizer': typeof OptimizerRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trucks': typeof TrucksRoute
  '/api/public/sensors': typeof ApiPublicSensorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/bins'
    | '/dashboard'
    | '/live-map'
    | '/optimizer'
    | '/reports'
    | '/settings'
    | '/trucks'
    | '/api/public/sensors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/bins'
    | '/dashboard'
    | '/live-map'
    | '/optimizer'
    | '/reports'
    | '/settings'
    | '/trucks'
    | '/api/public/sensors'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/bins'
    | '/dashboard'
    | '/live-map'
    | '/optimizer'
    | '/reports'
    | '/settings'
    | '/trucks'
    | '/api/public/sensors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  BinsRoute: typeof BinsRoute
  DashboardRoute: typeof DashboardRoute
  LiveMapRoute: typeof LiveMapRoute
  OptimizerRoute: typeof OptimizerRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TrucksRoute: typeof TrucksRoute
  ApiPublicSensorsRoute: typeof ApiPublicSensorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bins': {
      id: '/bins'
      path: '/bins'
      fullPath: '/bins'
      preLoaderRoute: typeof BinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks': {
      id: '/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof TrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sensors': {
      id: '/api/public/sensors'
      path: '/api/public/sensors'
      fullPath: '/api/public/sensors'
      preLoaderRoute: typeof ApiPublicSensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  BinsRoute: BinsRoute,
  DashboardRoute: DashboardRoute,
  LiveMapRoute: LiveMapRoute,
  OptimizerRoute: OptimizerRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TrucksRoute: TrucksRoute,
  ApiPublicSensorsRoute: ApiPublicSensorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
